# Generated by Django 4.2.1 on 2023-07-06 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authuser', '0005_bank_otp_userotp'),
    ]

    operations = [
        migrations.AddField(
            model_name='userotp',
            name='otp',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
