# Generated by Django 4.2.1 on 2023-07-06 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authuser', '0007_delete_userotp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bank',
            name='otp',
        ),
    ]
