# Generated by Django 4.2.1 on 2023-07-06 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authuser', '0008_remove_bank_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='bank',
            name='otp',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
