# Generated by Django 4.2.1 on 2023-07-11 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authuser', '0009_bank_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='wallet_balance',
            field=models.FloatField(default=0),
        ),
    ]
