# Generated by Django 4.2.1 on 2023-12-27 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authuser', '0010_user_wallet_balance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bank',
            name='otp',
        ),
    ]
