# Generated by Django 4.2.1 on 2023-06-06 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_rename_ordered_cart_completed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartproduct',
            old_name='ordered',
            new_name='completed',
        ),
    ]
