# Generated by Django 4.2.1 on 2023-06-06 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_rename_completed_cartproduct_ordered'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='ordered_date',
            new_name='created_at',
        ),
    ]
