# Generated by Django 4.2.1 on 2023-06-06 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_cartproduct_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartproduct',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='cartproduct',
            name='product',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='CartProduct',
        ),
    ]
