# Generated by Django 4.2.1 on 2023-07-04 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_alter_review_created_by_alter_review_image1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='image1',
            field=models.ImageField(upload_to='product_images'),
        ),
    ]
