# Generated by Django 4.2.1 on 2023-07-04 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_alter_review_image1'),
    ]

    operations = [
        migrations.AddField(
            model_name='subvariation',
            name='stock',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
