# Generated by Django 4.2.1 on 2023-07-09 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_product_discount_price_alter_product_price_and_more'),
        ('product', '0008_subvariation_stock'),
    ]

    operations = [
    ]
