# Generated by Django 4.2.1 on 2023-07-10 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_merge_20230709_1837'),
        ('product', '0009_merge_20230710_1532'),
    ]

    operations = [
    ]
