# Generated by Django 4.2.1 on 2023-07-10 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_merge_20230710_1929'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='number_sold',
            field=models.BigIntegerField(default=0),
        ),
    ]
