# Generated by Django 4.2.1 on 2023-07-20 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_product_sold_product_stock'),
        ('product', '0011_product_number_sold'),
    ]

    operations = [
    ]
