# Generated by Django 4.2.1 on 2024-01-01 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_variation_stock_delete_subvariation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='variation',
            old_name='type',
            new_name='option',
        ),
    ]
