# Generated by Django 4.2.1 on 2024-01-09 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0015_product_variation_bool'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='variation_bool',
        ),
    ]
