# Generated by Django 4.2.1 on 2023-07-02 07:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuyerStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'BuyerStatus',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='SellerStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'SellerStatus',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='OrderProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_number', models.CharField(default='', max_length=25)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=255)),
                ('price', models.FloatField()),
                ('thumbnail', models.ImageField(upload_to='product_images')),
                ('seller', models.CharField(max_length=255)),
                ('quantity', models.IntegerField()),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buyer', to=settings.AUTH_USER_MODEL)),
                ('buyer_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buyerstatus', to='checkout.buyerstatus')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='checkout.cartproduct')),
                ('seller_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sellerstatus', to='checkout.sellerstatus')),
            ],
        ),
    ]
