# Generated by Django 4.2.1 on 2023-07-02 10:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('checkout', '0004_alter_orderproduct_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproduct',
            name='seller_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='orderproduct',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seller', to=settings.AUTH_USER_MODEL),
        ),
    ]
