# Generated by Django 4.2.1 on 2023-07-02 12:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('checkout', '0005_orderproduct_seller_name_alter_orderproduct_seller'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproduct',
            name='buyer_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='orderproduct',
            name='buyer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='buyer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='orderproduct',
            name='cart_product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='checkout.cartproduct'),
        ),
        migrations.AlterField(
            model_name='orderproduct',
            name='seller',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seller', to=settings.AUTH_USER_MODEL),
        ),
    ]
