# Generated by Django 4.2.1 on 2023-07-03 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0006_orderproduct_buyer_name_alter_orderproduct_buyer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproduct',
            name='delivery_partner',
            field=models.CharField(default='', max_length=25),
        ),
    ]
