# Generated by Django 4.2.1 on 2023-07-05 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0007_orderproduct_delivery_partner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderproduct',
            name='buyer_name',
        ),
        migrations.RemoveField(
            model_name='orderproduct',
            name='seller_name',
        ),
    ]
