# Generated by Django 4.2.1 on 2023-07-09 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_cartproduct_variation'),
        ('checkout', '0008_remove_orderproduct_buyer_name_and_more'),
    ]

    operations = [
    ]
