# Generated by Django 4.2.1 on 2023-07-17 13:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('checkout', '0009_merge_20230709_1837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartproduct',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_product', to=settings.AUTH_USER_MODEL),
        ),
    ]
