# Generated by Django 4.2.1 on 2023-07-09 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0010_alter_cartproduct_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproduct',
            name='variation',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
