# Generated by Django 4.2.1 on 2023-07-11 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0011_orderproduct_variation'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproduct',
            name='saved',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='orderproduct',
            name='subtotal',
            field=models.FloatField(null=True),
        ),
    ]
