# Generated by Django 4.2.1 on 2023-07-20 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0009_merge_20230709_1828'),
        ('checkout', '0012_orderproduct_saved_orderproduct_subtotal'),
    ]

    operations = [
    ]
