# Generated by Django 4.2.1 on 2024-01-05 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_rename_type_variation_option'),
        ('checkout', '0013_merge_20230721_0031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartproduct',
            name='variation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variation', to='product.variation'),
        ),
    ]
