# Generated by Django 4.2.1 on 2023-07-02 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_product_discount_price_alter_product_price_and_more'),
        ('checkout', '0006_orderproduct_buyer_name_alter_orderproduct_buyer_and_more'),
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='order_product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chats', to='checkout.orderproduct'),
        ),
        migrations.AlterField(
            model_name='chat',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chats', to='product.product'),
        ),
    ]
